#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCoSoNghanh.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using System.ComponentModel.DataAnnotations.Schema;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DoAn")]
	public partial class TimViecDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertComment(Comment instance);
    partial void UpdateComment(Comment instance);
    partial void DeleteComment(Comment instance);
    partial void InsertViecLam(ViecLam instance);
    partial void UpdateViecLam(ViecLam instance);
    partial void DeleteViecLam(ViecLam instance);
    partial void InsertDatLich(DatLich instance);
    partial void UpdateDatLich(DatLich instance);
    partial void DeleteDatLich(DatLich instance);
    partial void InsertDonUngTuyen(DonUngTuyen instance);
    partial void UpdateDonUngTuyen(DonUngTuyen instance);
    partial void DeleteDonUngTuyen(DonUngTuyen instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiVieclam(LoaiVieclam instance);
    partial void UpdateLoaiVieclam(LoaiVieclam instance);
    partial void DeleteLoaiVieclam(LoaiVieclam instance);
    partial void InsertLuuViec(LuuViec instance);
    partial void UpdateLuuViec(LuuViec instance);
    partial void DeleteLuuViec(LuuViec instance);
    partial void InsertNhaTuyenDung(NhaTuyenDung instance);
    partial void UpdateNhaTuyenDung(NhaTuyenDung instance);
    partial void DeleteNhaTuyenDung(NhaTuyenDung instance);
    #endregion
		
		public TimViecDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimViecDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimViecDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
        public TimViecDataContext() :
         base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DoAnConnectionString3"].ConnectionString, mappingSource)
        {
            OnCreated();
        }
        public TimViecDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Comment> Comments
		{
			get
			{
				return this.GetTable<Comment>();
			}
		}
		
		public System.Data.Linq.Table<ViecLam> ViecLams
		{
			get
			{
				return this.GetTable<ViecLam>();
			}
		}
		
		public System.Data.Linq.Table<DatLich> DatLiches
		{
			get
			{
				return this.GetTable<DatLich>();
			}
		}
		
		public System.Data.Linq.Table<DonUngTuyen> DonUngTuyens
		{
			get
			{
				return this.GetTable<DonUngTuyen>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiVieclam> LoaiVieclams
		{
			get
			{
				return this.GetTable<LoaiVieclam>();
			}
		}
		
		public System.Data.Linq.Table<LuuViec> LuuViecs
		{
			get
			{
				return this.GetTable<LuuViec>();
			}
		}
		
		public System.Data.Linq.Table<NhaTuyenDung> NhaTuyenDungs
		{
			get
			{
				return this.GetTable<NhaTuyenDung>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comments")]
	public partial class Comment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CommentID;
		
		private int _MaKH;
		
		private string _Content;
		
		private System.Nullable<System.DateTime> _CommentTime;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCommentIDChanging(int value);
    partial void OnCommentIDChanged();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnCommentTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCommentTimeChanged();
    #endregion
		
		public Comment()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CommentID
		{
			get
			{
				return this._CommentID;
			}
			set
			{
				if ((this._CommentID != value))
				{
					this.OnCommentIDChanging(value);
					this.SendPropertyChanging();
					this._CommentID = value;
					this.SendPropertyChanged("CommentID");
					this.OnCommentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CommentTime
		{
			get
			{
				return this._CommentTime;
			}
			set
			{
				if ((this._CommentTime != value))
				{
					this.OnCommentTimeChanging(value);
					this.SendPropertyChanging();
					this._CommentTime = value;
					this.SendPropertyChanged("CommentTime");
					this.OnCommentTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_Comment", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.Comments.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.Comments.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViecLam")]
	public partial class ViecLam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCongViec;
		
		private string _TenVieclam;
		
		private string _DiaDiemLamViec;
		
		private string _LoaiViecLam;
		
		private System.Nullable<decimal> _Luong;
		
		private string _MoTaCongViec;
		
		private string _YeuCauCongViec;
		
		private string _QuyenLoiCongViec;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private System.Nullable<System.DateTime> _NgayHetHan;
		
		private string _Hinh;
		
		private System.Nullable<int> _TrangThai;
		
		private System.Nullable<int> _MaNTD;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<int> _Mal;
		
		private EntitySet<DonUngTuyen> _DonUngTuyens;
		
		private EntitySet<LuuViec> _LuuViecs;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<LoaiVieclam> _LoaiVieclam1;
		
		private EntityRef<NhaTuyenDung> _NhaTuyenDung;

		
        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }

        #region Extensibility Method Definitions
        partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCongViecChanging(int value);
    partial void OnMaCongViecChanged();
    partial void OnTenVieclamChanging(string value);
    partial void OnTenVieclamChanged();
    partial void OnDiaDiemLamViecChanging(string value);
    partial void OnDiaDiemLamViecChanged();
    partial void OnLoaiViecLamChanging(string value);
    partial void OnLoaiViecLamChanged();
    partial void OnLuongChanging(System.Nullable<decimal> value);
    partial void OnLuongChanged();
    partial void OnMoTaCongViecChanging(string value);
    partial void OnMoTaCongViecChanged();
    partial void OnYeuCauCongViecChanging(string value);
    partial void OnYeuCauCongViecChanged();
    partial void OnQuyenLoiCongViecChanging(string value);
    partial void OnQuyenLoiCongViecChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnNgayHetHanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanChanged();
    partial void OnHinhChanging(string value);
    partial void OnHinhChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    partial void OnMaNTDChanging(System.Nullable<int> value);
    partial void OnMaNTDChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnMalChanging(System.Nullable<int> value);
    partial void OnMalChanged();
    #endregion
		
		public ViecLam()
		{
			this._DonUngTuyens = new EntitySet<DonUngTuyen>(new Action<DonUngTuyen>(this.attach_DonUngTuyens), new Action<DonUngTuyen>(this.detach_DonUngTuyens));
			this._LuuViecs = new EntitySet<LuuViec>(new Action<LuuViec>(this.attach_LuuViecs), new Action<LuuViec>(this.detach_LuuViecs));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._LoaiVieclam1 = default(EntityRef<LoaiVieclam>);
			this._NhaTuyenDung = default(EntityRef<NhaTuyenDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongViec", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCongViec
		{
			get
			{
				return this._MaCongViec;
			}
			set
			{
				if ((this._MaCongViec != value))
				{
					this.OnMaCongViecChanging(value);
					this.SendPropertyChanging();
					this._MaCongViec = value;
					this.SendPropertyChanged("MaCongViec");
					this.OnMaCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVieclam", DbType="NVarChar(MAX)")]
		public string TenVieclam
		{
			get
			{
				return this._TenVieclam;
			}
			set
			{
				if ((this._TenVieclam != value))
				{
					this.OnTenVieclamChanging(value);
					this.SendPropertyChanging();
					this._TenVieclam = value;
					this.SendPropertyChanged("TenVieclam");
					this.OnTenVieclamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiemLamViec", DbType="NVarChar(MAX)")]
		public string DiaDiemLamViec
		{
			get
			{
				return this._DiaDiemLamViec;
			}
			set
			{
				if ((this._DiaDiemLamViec != value))
				{
					this.OnDiaDiemLamViecChanging(value);
					this.SendPropertyChanging();
					this._DiaDiemLamViec = value;
					this.SendPropertyChanged("DiaDiemLamViec");
					this.OnDiaDiemLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiViecLam", DbType="NVarChar(MAX)")]
		public string LoaiViecLam
		{
			get
			{
				return this._LoaiViecLam;
			}
			set
			{
				if ((this._LoaiViecLam != value))
				{
					this.OnLoaiViecLamChanging(value);
					this.SendPropertyChanging();
					this._LoaiViecLam = value;
					this.SendPropertyChanged("LoaiViecLam");
					this.OnLoaiViecLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="Money")]
		public System.Nullable<decimal> Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaCongViec", DbType="NVarChar(MAX)")]
		public string MoTaCongViec
		{
			get
			{
				return this._MoTaCongViec;
			}
			set
			{
				if ((this._MoTaCongViec != value))
				{
					this.OnMoTaCongViecChanging(value);
					this.SendPropertyChanging();
					this._MoTaCongViec = value;
					this.SendPropertyChanged("MoTaCongViec");
					this.OnMoTaCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauCongViec", DbType="NVarChar(MAX)")]
		public string YeuCauCongViec
		{
			get
			{
				return this._YeuCauCongViec;
			}
			set
			{
				if ((this._YeuCauCongViec != value))
				{
					this.OnYeuCauCongViecChanging(value);
					this.SendPropertyChanging();
					this._YeuCauCongViec = value;
					this.SendPropertyChanged("YeuCauCongViec");
					this.OnYeuCauCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenLoiCongViec", DbType="NVarChar(MAX)")]
		public string QuyenLoiCongViec
		{
			get
			{
				return this._QuyenLoiCongViec;
			}
			set
			{
				if ((this._QuyenLoiCongViec != value))
				{
					this.OnQuyenLoiCongViecChanging(value);
					this.SendPropertyChanging();
					this._QuyenLoiCongViec = value;
					this.SendPropertyChanged("QuyenLoiCongViec");
					this.OnQuyenLoiCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh", DbType="NVarChar(MAX)")]
		public string Hinh
		{
			get
			{
				return this._Hinh;
			}
			set
			{
				if ((this._Hinh != value))
				{
					this.OnHinhChanging(value);
					this.SendPropertyChanging();
					this._Hinh = value;
					this.SendPropertyChanged("Hinh");
					this.OnHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNTD", DbType="Int")]
		public System.Nullable<int> MaNTD
		{
			get
			{
				return this._MaNTD;
			}
			set
			{
				if ((this._MaNTD != value))
				{
					if (this._NhaTuyenDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNTDChanging(value);
					this.SendPropertyChanging();
					this._MaNTD = value;
					this.SendPropertyChanged("MaNTD");
					this.OnMaNTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mal", DbType="Int")]
		public System.Nullable<int> Mal
		{
			get
			{
				return this._Mal;
			}
			set
			{
				if ((this._Mal != value))
				{
					if (this._LoaiVieclam1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMalChanging(value);
					this.SendPropertyChanging();
					this._Mal = value;
					this.SendPropertyChanged("Mal");
					this.OnMalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ViecLam_DonUngTuyen", Storage="_DonUngTuyens", ThisKey="MaCongViec", OtherKey="MaCongViec")]
		public EntitySet<DonUngTuyen> DonUngTuyens
		{
			get
			{
				return this._DonUngTuyens;
			}
			set
			{
				this._DonUngTuyens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ViecLam_LuuViec", Storage="_LuuViecs", ThisKey="MaCongViec", OtherKey="MaCongViec")]
		public EntitySet<LuuViec> LuuViecs
		{
			get
			{
				return this._LuuViecs;
			}
			set
			{
				this._LuuViecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_ViecLam", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.ViecLams.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.ViecLams.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiVieclam_ViecLam", Storage="_LoaiVieclam1", ThisKey="Mal", OtherKey="Mal", IsForeignKey=true)]
		public LoaiVieclam LoaiVieclam1
		{
			get
			{
				return this._LoaiVieclam1.Entity;
			}
			set
			{
				LoaiVieclam previousValue = this._LoaiVieclam1.Entity;
				if (((previousValue != value) 
							|| (this._LoaiVieclam1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiVieclam1.Entity = null;
						previousValue.ViecLams.Remove(this);
					}
					this._LoaiVieclam1.Entity = value;
					if ((value != null))
					{
						value.ViecLams.Add(this);
						this._Mal = value.Mal;
					}
					else
					{
						this._Mal = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiVieclam1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_ViecLam", Storage="_NhaTuyenDung", ThisKey="MaNTD", OtherKey="MaNTD", IsForeignKey=true)]
		public NhaTuyenDung NhaTuyenDung
		{
			get
			{
				return this._NhaTuyenDung.Entity;
			}
			set
			{
				NhaTuyenDung previousValue = this._NhaTuyenDung.Entity;
				if (((previousValue != value) 
							|| (this._NhaTuyenDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaTuyenDung.Entity = null;
						previousValue.ViecLams.Remove(this);
					}
					this._NhaTuyenDung.Entity = value;
					if ((value != null))
					{
						value.ViecLams.Add(this);
						this._MaNTD = value.MaNTD;
					}
					else
					{
						this._MaNTD = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhaTuyenDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonUngTuyens(DonUngTuyen entity)
		{
			this.SendPropertyChanging();
			entity.ViecLam = this;
		}
		
		private void detach_DonUngTuyens(DonUngTuyen entity)
		{
			this.SendPropertyChanging();
			entity.ViecLam = null;
		}
		
		private void attach_LuuViecs(LuuViec entity)
		{
			this.SendPropertyChanging();
			entity.ViecLam = this;
		}
		
		private void detach_LuuViecs(LuuViec entity)
		{
			this.SendPropertyChanging();
			entity.ViecLam = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DatLich")]
	public partial class DatLich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDatLich;
		
		private System.Nullable<System.DateTime> _NgayDatLich;
		
		private System.Nullable<int> _MaNTD;
		
		private EntityRef<NhaTuyenDung> _NhaTuyenDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDatLichChanging(int value);
    partial void OnMaDatLichChanged();
    partial void OnNgayDatLichChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatLichChanged();
    partial void OnMaNTDChanging(System.Nullable<int> value);
    partial void OnMaNTDChanged();
    #endregion
		
		public DatLich()
		{
			this._NhaTuyenDung = default(EntityRef<NhaTuyenDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDatLich", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDatLich
		{
			get
			{
				return this._MaDatLich;
			}
			set
			{
				if ((this._MaDatLich != value))
				{
					this.OnMaDatLichChanging(value);
					this.SendPropertyChanging();
					this._MaDatLich = value;
					this.SendPropertyChanged("MaDatLich");
					this.OnMaDatLichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDatLich", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDatLich
		{
			get
			{
				return this._NgayDatLich;
			}
			set
			{
				if ((this._NgayDatLich != value))
				{
					this.OnNgayDatLichChanging(value);
					this.SendPropertyChanging();
					this._NgayDatLich = value;
					this.SendPropertyChanged("NgayDatLich");
					this.OnNgayDatLichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNTD", DbType="Int")]
		public System.Nullable<int> MaNTD
		{
			get
			{
				return this._MaNTD;
			}
			set
			{
				if ((this._MaNTD != value))
				{
					if (this._NhaTuyenDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNTDChanging(value);
					this.SendPropertyChanging();
					this._MaNTD = value;
					this.SendPropertyChanged("MaNTD");
					this.OnMaNTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_DatLich", Storage="_NhaTuyenDung", ThisKey="MaNTD", OtherKey="MaNTD", IsForeignKey=true)]
		public NhaTuyenDung NhaTuyenDung
		{
			get
			{
				return this._NhaTuyenDung.Entity;
			}
			set
			{
				NhaTuyenDung previousValue = this._NhaTuyenDung.Entity;
				if (((previousValue != value) 
							|| (this._NhaTuyenDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaTuyenDung.Entity = null;
						previousValue.DatLiches.Remove(this);
					}
					this._NhaTuyenDung.Entity = value;
					if ((value != null))
					{
						value.DatLiches.Add(this);
						this._MaNTD = value.MaNTD;
					}
					else
					{
						this._MaNTD = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhaTuyenDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonUngTuyen")]
	public partial class DonUngTuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonUngTuyen;
		
		private System.Nullable<int> _MaCongViec;
		
		private System.Nullable<int> _TrangThaiDonUngTuyen;
		
		private System.Nullable<System.DateTime> _NgayNop;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<int> _MaNTD;
		
		private string _TenNguoiUngTuyen;
		
		private string _EmailNguoiUngTuyen;
		
		private string _NoiDung;
		
		private string _FileCV;
		
		private System.Nullable<System.DateTime> _NgayDuKienDenCongTy;
		
		private string _NoiDungGuiToiKhachHang;
		
		private EntityRef<ViecLam> _ViecLam;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhaTuyenDung> _NhaTuyenDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonUngTuyenChanging(int value);
    partial void OnMaDonUngTuyenChanged();
    partial void OnMaCongViecChanging(System.Nullable<int> value);
    partial void OnMaCongViecChanged();
    partial void OnTrangThaiDonUngTuyenChanging(System.Nullable<int> value);
    partial void OnTrangThaiDonUngTuyenChanged();
    partial void OnNgayNopChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNopChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnMaNTDChanging(System.Nullable<int> value);
    partial void OnMaNTDChanged();
    partial void OnTenNguoiUngTuyenChanging(string value);
    partial void OnTenNguoiUngTuyenChanged();
    partial void OnEmailNguoiUngTuyenChanging(string value);
    partial void OnEmailNguoiUngTuyenChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnFileCVChanging(string value);
    partial void OnFileCVChanged();
    partial void OnNgayDuKienDenCongTyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDuKienDenCongTyChanged();
    partial void OnNoiDungGuiToiKhachHangChanging(string value);
    partial void OnNoiDungGuiToiKhachHangChanged();
    #endregion
		
		public DonUngTuyen()
		{
			this._ViecLam = default(EntityRef<ViecLam>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhaTuyenDung = default(EntityRef<NhaTuyenDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonUngTuyen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDonUngTuyen
		{
			get
			{
				return this._MaDonUngTuyen;
			}
			set
			{
				if ((this._MaDonUngTuyen != value))
				{
					this.OnMaDonUngTuyenChanging(value);
					this.SendPropertyChanging();
					this._MaDonUngTuyen = value;
					this.SendPropertyChanged("MaDonUngTuyen");
					this.OnMaDonUngTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongViec", DbType="Int")]
		public System.Nullable<int> MaCongViec
		{
			get
			{
				return this._MaCongViec;
			}
			set
			{
				if ((this._MaCongViec != value))
				{
					if (this._ViecLam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCongViecChanging(value);
					this.SendPropertyChanging();
					this._MaCongViec = value;
					this.SendPropertyChanged("MaCongViec");
					this.OnMaCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiDonUngTuyen", DbType="Int")]
		public System.Nullable<int> TrangThaiDonUngTuyen
		{
			get
			{
				return this._TrangThaiDonUngTuyen;
			}
			set
			{
				if ((this._TrangThaiDonUngTuyen != value))
				{
					this.OnTrangThaiDonUngTuyenChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiDonUngTuyen = value;
					this.SendPropertyChanged("TrangThaiDonUngTuyen");
					this.OnTrangThaiDonUngTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNop", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNop
		{
			get
			{
				return this._NgayNop;
			}
			set
			{
				if ((this._NgayNop != value))
				{
					this.OnNgayNopChanging(value);
					this.SendPropertyChanging();
					this._NgayNop = value;
					this.SendPropertyChanged("NgayNop");
					this.OnNgayNopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNTD", DbType="Int")]
		public System.Nullable<int> MaNTD
		{
			get
			{
				return this._MaNTD;
			}
			set
			{
				if ((this._MaNTD != value))
				{
					if (this._NhaTuyenDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNTDChanging(value);
					this.SendPropertyChanging();
					this._MaNTD = value;
					this.SendPropertyChanged("MaNTD");
					this.OnMaNTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiUngTuyen", DbType="NVarChar(MAX)")]
		public string TenNguoiUngTuyen
		{
			get
			{
				return this._TenNguoiUngTuyen;
			}
			set
			{
				if ((this._TenNguoiUngTuyen != value))
				{
					this.OnTenNguoiUngTuyenChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiUngTuyen = value;
					this.SendPropertyChanged("TenNguoiUngTuyen");
					this.OnTenNguoiUngTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailNguoiUngTuyen", DbType="NVarChar(MAX)")]
		public string EmailNguoiUngTuyen
		{
			get
			{
				return this._EmailNguoiUngTuyen;
			}
			set
			{
				if ((this._EmailNguoiUngTuyen != value))
				{
					this.OnEmailNguoiUngTuyenChanging(value);
					this.SendPropertyChanging();
					this._EmailNguoiUngTuyen = value;
					this.SendPropertyChanged("EmailNguoiUngTuyen");
					this.OnEmailNguoiUngTuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileCV", DbType="NVarChar(MAX)")]
		public string FileCV
		{
			get
			{
				return this._FileCV;
			}
			set
			{
				if ((this._FileCV != value))
				{
					this.OnFileCVChanging(value);
					this.SendPropertyChanging();
					this._FileCV = value;
					this.SendPropertyChanged("FileCV");
					this.OnFileCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDuKienDenCongTy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDuKienDenCongTy
		{
			get
			{
				return this._NgayDuKienDenCongTy;
			}
			set
			{
				if ((this._NgayDuKienDenCongTy != value))
				{
					this.OnNgayDuKienDenCongTyChanging(value);
					this.SendPropertyChanging();
					this._NgayDuKienDenCongTy = value;
					this.SendPropertyChanged("NgayDuKienDenCongTy");
					this.OnNgayDuKienDenCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungGuiToiKhachHang", DbType="NVarChar(MAX)")]
		public string NoiDungGuiToiKhachHang
		{
			get
			{
				return this._NoiDungGuiToiKhachHang;
			}
			set
			{
				if ((this._NoiDungGuiToiKhachHang != value))
				{
					this.OnNoiDungGuiToiKhachHangChanging(value);
					this.SendPropertyChanging();
					this._NoiDungGuiToiKhachHang = value;
					this.SendPropertyChanged("NoiDungGuiToiKhachHang");
					this.OnNoiDungGuiToiKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ViecLam_DonUngTuyen", Storage="_ViecLam", ThisKey="MaCongViec", OtherKey="MaCongViec", IsForeignKey=true)]
		public ViecLam ViecLam
		{
			get
			{
				return this._ViecLam.Entity;
			}
			set
			{
				ViecLam previousValue = this._ViecLam.Entity;
				if (((previousValue != value) 
							|| (this._ViecLam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ViecLam.Entity = null;
						previousValue.DonUngTuyens.Remove(this);
					}
					this._ViecLam.Entity = value;
					if ((value != null))
					{
						value.DonUngTuyens.Add(this);
						this._MaCongViec = value.MaCongViec;
					}
					else
					{
						this._MaCongViec = default(Nullable<int>);
					}
					this.SendPropertyChanged("ViecLam");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonUngTuyen", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DonUngTuyens.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DonUngTuyens.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_DonUngTuyen", Storage="_NhaTuyenDung", ThisKey="MaNTD", OtherKey="MaNTD", IsForeignKey=true)]
		public NhaTuyenDung NhaTuyenDung
		{
			get
			{
				return this._NhaTuyenDung.Entity;
			}
			set
			{
				NhaTuyenDung previousValue = this._NhaTuyenDung.Entity;
				if (((previousValue != value) 
							|| (this._NhaTuyenDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaTuyenDung.Entity = null;
						previousValue.DonUngTuyens.Remove(this);
					}
					this._NhaTuyenDung.Entity = value;
					if ((value != null))
					{
						value.DonUngTuyens.Add(this);
						this._MaNTD = value.MaNTD;
					}
					else
					{
						this._MaNTD = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhaTuyenDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _HoTen;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<int> _IDQuyen;
		
		private EntitySet<Comment> _Comments;
		
		private EntitySet<ViecLam> _ViecLams;
		
		private EntitySet<DonUngTuyen> _DonUngTuyens;
		
		private EntitySet<LuuViec> _LuuViecs;
		
		private EntitySet<NhaTuyenDung> _NhaTuyenDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnIDQuyenChanging(System.Nullable<int> value);
    partial void OnIDQuyenChanged();
    #endregion
		
		public KhachHang()
		{
			this._Comments = new EntitySet<Comment>(new Action<Comment>(this.attach_Comments), new Action<Comment>(this.detach_Comments));
			this._ViecLams = new EntitySet<ViecLam>(new Action<ViecLam>(this.attach_ViecLams), new Action<ViecLam>(this.detach_ViecLams));
			this._DonUngTuyens = new EntitySet<DonUngTuyen>(new Action<DonUngTuyen>(this.attach_DonUngTuyens), new Action<DonUngTuyen>(this.detach_DonUngTuyens));
			this._LuuViecs = new EntitySet<LuuViec>(new Action<LuuViec>(this.attach_LuuViecs), new Action<LuuViec>(this.detach_LuuViecs));
			this._NhaTuyenDungs = new EntitySet<NhaTuyenDung>(new Action<NhaTuyenDung>(this.attach_NhaTuyenDungs), new Action<NhaTuyenDung>(this.detach_NhaTuyenDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDQuyen", DbType="Int")]
		public System.Nullable<int> IDQuyen
		{
			get
			{
				return this._IDQuyen;
			}
			set
			{
				if ((this._IDQuyen != value))
				{
					this.OnIDQuyenChanging(value);
					this.SendPropertyChanging();
					this._IDQuyen = value;
					this.SendPropertyChanged("IDQuyen");
					this.OnIDQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_Comment", Storage="_Comments", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<Comment> Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				this._Comments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_ViecLam", Storage="_ViecLams", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<ViecLam> ViecLams
		{
			get
			{
				return this._ViecLams;
			}
			set
			{
				this._ViecLams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonUngTuyen", Storage="_DonUngTuyens", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<DonUngTuyen> DonUngTuyens
		{
			get
			{
				return this._DonUngTuyens;
			}
			set
			{
				this._DonUngTuyens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_LuuViec", Storage="_LuuViecs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<LuuViec> LuuViecs
		{
			get
			{
				return this._LuuViecs;
			}
			set
			{
				this._LuuViecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_NhaTuyenDung", Storage="_NhaTuyenDungs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<NhaTuyenDung> NhaTuyenDungs
		{
			get
			{
				return this._NhaTuyenDungs;
			}
			set
			{
				this._NhaTuyenDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comments(Comment entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_Comments(Comment entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_ViecLams(ViecLam entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_ViecLams(ViecLam entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_DonUngTuyens(DonUngTuyen entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DonUngTuyens(DonUngTuyen entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_LuuViecs(LuuViec entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_LuuViecs(LuuViec entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_NhaTuyenDungs(NhaTuyenDung entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_NhaTuyenDungs(NhaTuyenDung entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiVieclam")]
	public partial class LoaiVieclam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mal;
		
		private string _TenLoai;
		
		private string _Icon;
		
		private EntitySet<ViecLam> _ViecLams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMalChanging(int value);
    partial void OnMalChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnIconChanging(string value);
    partial void OnIconChanged();
    #endregion
		
		public LoaiVieclam()
		{
			this._ViecLams = new EntitySet<ViecLam>(new Action<ViecLam>(this.attach_ViecLams), new Action<ViecLam>(this.detach_ViecLams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mal", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mal
		{
			get
			{
				return this._Mal;
			}
			set
			{
				if ((this._Mal != value))
				{
					this.OnMalChanging(value);
					this.SendPropertyChanging();
					this._Mal = value;
					this.SendPropertyChanged("Mal");
					this.OnMalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(MAX)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="NVarChar(MAX)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this.OnIconChanging(value);
					this.SendPropertyChanging();
					this._Icon = value;
					this.SendPropertyChanged("Icon");
					this.OnIconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiVieclam_ViecLam", Storage="_ViecLams", ThisKey="Mal", OtherKey="Mal")]
		public EntitySet<ViecLam> ViecLams
		{
			get
			{
				return this._ViecLams;
			}
			set
			{
				this._ViecLams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ViecLams(ViecLam entity)
		{
			this.SendPropertyChanging();
			entity.LoaiVieclam1 = this;
		}
		
		private void detach_ViecLams(ViecLam entity)
		{
			this.SendPropertyChanging();
			entity.LoaiVieclam1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LuuViec")]
	public partial class LuuViec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLuuViec;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<int> _MaCongViec;
		
		private System.Nullable<int> _MaNTD;
		
		private EntityRef<ViecLam> _ViecLam;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhaTuyenDung> _NhaTuyenDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLuuViecChanging(int value);
    partial void OnMaLuuViecChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnMaCongViecChanging(System.Nullable<int> value);
    partial void OnMaCongViecChanged();
    partial void OnMaNTDChanging(System.Nullable<int> value);
    partial void OnMaNTDChanged();
    #endregion
		
		public LuuViec()
		{
			this._ViecLam = default(EntityRef<ViecLam>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhaTuyenDung = default(EntityRef<NhaTuyenDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLuuViec", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLuuViec
		{
			get
			{
				return this._MaLuuViec;
			}
			set
			{
				if ((this._MaLuuViec != value))
				{
					this.OnMaLuuViecChanging(value);
					this.SendPropertyChanging();
					this._MaLuuViec = value;
					this.SendPropertyChanged("MaLuuViec");
					this.OnMaLuuViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongViec", DbType="Int")]
		public System.Nullable<int> MaCongViec
		{
			get
			{
				return this._MaCongViec;
			}
			set
			{
				if ((this._MaCongViec != value))
				{
					if (this._ViecLam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCongViecChanging(value);
					this.SendPropertyChanging();
					this._MaCongViec = value;
					this.SendPropertyChanged("MaCongViec");
					this.OnMaCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNTD", DbType="Int")]
		public System.Nullable<int> MaNTD
		{
			get
			{
				return this._MaNTD;
			}
			set
			{
				if ((this._MaNTD != value))
				{
					if (this._NhaTuyenDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNTDChanging(value);
					this.SendPropertyChanging();
					this._MaNTD = value;
					this.SendPropertyChanged("MaNTD");
					this.OnMaNTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ViecLam_LuuViec", Storage="_ViecLam", ThisKey="MaCongViec", OtherKey="MaCongViec", IsForeignKey=true)]
		public ViecLam ViecLam
		{
			get
			{
				return this._ViecLam.Entity;
			}
			set
			{
				ViecLam previousValue = this._ViecLam.Entity;
				if (((previousValue != value) 
							|| (this._ViecLam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ViecLam.Entity = null;
						previousValue.LuuViecs.Remove(this);
					}
					this._ViecLam.Entity = value;
					if ((value != null))
					{
						value.LuuViecs.Add(this);
						this._MaCongViec = value.MaCongViec;
					}
					else
					{
						this._MaCongViec = default(Nullable<int>);
					}
					this.SendPropertyChanged("ViecLam");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_LuuViec", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.LuuViecs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.LuuViecs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_LuuViec", Storage="_NhaTuyenDung", ThisKey="MaNTD", OtherKey="MaNTD", IsForeignKey=true)]
		public NhaTuyenDung NhaTuyenDung
		{
			get
			{
				return this._NhaTuyenDung.Entity;
			}
			set
			{
				NhaTuyenDung previousValue = this._NhaTuyenDung.Entity;
				if (((previousValue != value) 
							|| (this._NhaTuyenDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaTuyenDung.Entity = null;
						previousValue.LuuViecs.Remove(this);
					}
					this._NhaTuyenDung.Entity = value;
					if ((value != null))
					{
						value.LuuViecs.Add(this);
						this._MaNTD = value.MaNTD;
					}
					else
					{
						this._MaNTD = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhaTuyenDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaTuyenDung")]
	public partial class NhaTuyenDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNTD;
		
		private string _TenCongTy;
		
		private string _MoTaCongTy;
		
		private string _Hinh;
		
		private System.Nullable<int> _MaKH;
		
		private EntitySet<ViecLam> _ViecLams;
		
		private EntitySet<DatLich> _DatLiches;
		
		private EntitySet<DonUngTuyen> _DonUngTuyens;
		
		private EntitySet<LuuViec> _LuuViecs;
		
		private EntityRef<KhachHang> _KhachHang;


        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }

        #region Extensibility Method Definitions
        partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNTDChanging(int value);
    partial void OnMaNTDChanged();
    partial void OnTenCongTyChanging(string value);
    partial void OnTenCongTyChanged();
    partial void OnMoTaCongTyChanging(string value);
    partial void OnMoTaCongTyChanged();
    partial void OnHinhChanging(string value);
    partial void OnHinhChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    #endregion
		
		public NhaTuyenDung()
		{
			this._ViecLams = new EntitySet<ViecLam>(new Action<ViecLam>(this.attach_ViecLams), new Action<ViecLam>(this.detach_ViecLams));
			this._DatLiches = new EntitySet<DatLich>(new Action<DatLich>(this.attach_DatLiches), new Action<DatLich>(this.detach_DatLiches));
			this._DonUngTuyens = new EntitySet<DonUngTuyen>(new Action<DonUngTuyen>(this.attach_DonUngTuyens), new Action<DonUngTuyen>(this.detach_DonUngTuyens));
			this._LuuViecs = new EntitySet<LuuViec>(new Action<LuuViec>(this.attach_LuuViecs), new Action<LuuViec>(this.detach_LuuViecs));
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNTD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNTD
		{
			get
			{
				return this._MaNTD;
			}
			set
			{
				if ((this._MaNTD != value))
				{
					this.OnMaNTDChanging(value);
					this.SendPropertyChanging();
					this._MaNTD = value;
					this.SendPropertyChanged("MaNTD");
					this.OnMaNTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTy", DbType="NVarChar(MAX)")]
		public string TenCongTy
		{
			get
			{
				return this._TenCongTy;
			}
			set
			{
				if ((this._TenCongTy != value))
				{
					this.OnTenCongTyChanging(value);
					this.SendPropertyChanging();
					this._TenCongTy = value;
					this.SendPropertyChanged("TenCongTy");
					this.OnTenCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaCongTy", DbType="NVarChar(MAX)")]
		public string MoTaCongTy
		{
			get
			{
				return this._MoTaCongTy;
			}
			set
			{
				if ((this._MoTaCongTy != value))
				{
					this.OnMoTaCongTyChanging(value);
					this.SendPropertyChanging();
					this._MoTaCongTy = value;
					this.SendPropertyChanged("MoTaCongTy");
					this.OnMoTaCongTyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh", DbType="NVarChar(MAX)")]
		public string Hinh
		{
			get
			{
				return this._Hinh;
			}
			set
			{
				if ((this._Hinh != value))
				{
					this.OnHinhChanging(value);
					this.SendPropertyChanging();
					this._Hinh = value;
					this.SendPropertyChanged("Hinh");
					this.OnHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_ViecLam", Storage="_ViecLams", ThisKey="MaNTD", OtherKey="MaNTD")]
		public EntitySet<ViecLam> ViecLams
		{
			get
			{
				return this._ViecLams;
			}
			set
			{
				this._ViecLams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_DatLich", Storage="_DatLiches", ThisKey="MaNTD", OtherKey="MaNTD")]
		public EntitySet<DatLich> DatLiches
		{
			get
			{
				return this._DatLiches;
			}
			set
			{
				this._DatLiches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_DonUngTuyen", Storage="_DonUngTuyens", ThisKey="MaNTD", OtherKey="MaNTD")]
		public EntitySet<DonUngTuyen> DonUngTuyens
		{
			get
			{
				return this._DonUngTuyens;
			}
			set
			{
				this._DonUngTuyens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaTuyenDung_LuuViec", Storage="_LuuViecs", ThisKey="MaNTD", OtherKey="MaNTD")]
		public EntitySet<LuuViec> LuuViecs
		{
			get
			{
				return this._LuuViecs;
			}
			set
			{
				this._LuuViecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_NhaTuyenDung", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.NhaTuyenDungs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.NhaTuyenDungs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ViecLams(ViecLam entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = this;
		}
		
		private void detach_ViecLams(ViecLam entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = null;
		}
		
		private void attach_DatLiches(DatLich entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = this;
		}
		
		private void detach_DatLiches(DatLich entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = null;
		}
		
		private void attach_DonUngTuyens(DonUngTuyen entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = this;
		}
		
		private void detach_DonUngTuyens(DonUngTuyen entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = null;
		}
		
		private void attach_LuuViecs(LuuViec entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = this;
		}
		
		private void detach_LuuViecs(LuuViec entity)
		{
			this.SendPropertyChanging();
			entity.NhaTuyenDung = null;
		}
	}
}
#pragma warning restore 1591
